version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install sphinx-inline-tabs sphinx-copybutton furo sphinxcontrib-towncrier pydantic

sphinx:
  configuration: docs/conf.py

formats: all
